# HOUSE CONSTRUCTION PROJECT — FULL CONTEXT FOR CONTINUATION (v4)

## PROJECT OVERVIEW
- **Location:** Bhagamandala–Talakaveri Road (on a CURVE), Kodagu, Karnataka
- **3 km from Talakaveri temple**, left side when traveling to temple
- **Coffee plantation** below (west), road on east. **Isolated, no neighbors.**
- **Plot:** 60 ft (E-W) × 50 ft (N-S), East-facing, highway on East
- **Building:** G+1, 42 ft (N-S) × 38 ft (E-W) total (incl. 8 ft veranda)
- **Style:** Traditional Kodagu with Mangalore tile hip roof, laterite walls
- **Budget:** ~₹1 Crore (v4 all-inclusive)
- **Version:** v4 — Major layout redesign (April 2026)

## v4 KEY CHANGES FROM v3
1. Building widened: 42×38 (was 40×32) = +490 sqft
2. Bedrooms: FULL RECTANGLES (were L-shaped in v3 due to carved-in baths)
3. Baths: ALL 7×10 = 70 sqft (v3 had 48/35/48 sqft — Bath2 was cramped)
4. Back-to-back bath core: Single plumbing stack (saves ₹30-40K)
5. Kitchen ADJACENT to Store (shared wall with door)
6. FF: Dedicated Work Room 14×10 (140 sqft) — user works remotely for months
7. Sitout: ONE 26×8 (208 sqft) replaces 2 small balconies (156 sqft total)
8. Sitout faces WEST (plantation + hill views), supported by 3 pillars below
9. Comprehensive safety: 7' solid wall (road), CCTV 4 cameras, MS grills ALL windows, motion lights
10. Total: ~2,909 sqft built-up (was ~2,222)

## GF LAYOUT (42 N-S × 30 E-W interior + 8 ft veranda East)
- **North row (16ft):** Hall 16×16 (NE, 256) + BR2 14×16 (NW, 224)
- **Service strip (10ft):** Store 8×10 (W) + Bath2 7×10 + Pass 3×10 + Bath1 7×10 + Stair 5×10 (E)
- **South row (16ft):** Kitchen 14×16 (SE, 224) + Master 16×16 (SW, 256)
- **Veranda:** 42×8 (East) with GWC 4×4 in NE corner, 5 wooden pillars

## FF LAYOUT (26 N-S × 30 E-W + 8 ft sitout West)
- **North strip (10ft):** Work 14×10 + Pass 4×10 + Bath3 7×10 + Stair 5×10
- **South row (16ft):** Family Hall 14×16 (SE, 224) + Master 16×16 (SW, 256)
- **Sitout:** 26×8 (West), 3.5ft parapet + 6ft MS grill screen

## TERRACE: 12×10 partial over staircase, accessed via 3rd flight

## SAFETY FEATURES (Isolated highway curve location)
- 7 ft solid laterite compound wall (road side — crash protection)
- 6 ft solid walls (all other sides — no MS railing, full solid)
- CCTV: 4 cameras with DVR
- Motion sensor LED floods (front + back)
- MS grills: ALL windows, 12mm bars, 100mm spacing
- Reflectors on compound wall (highway night visibility)
- Gate set back from curve apex
- Sitout: 3.5ft parapet + 6ft grill = 9.5ft barrier

## FILES
- `generate_plans_v4.py` — Image generator (6 PNGs: GF, FF, Site, FrontElev, BackElev, Roof)
  - Now imports `from datetime import date`, auto-stamps all images: `"DD Month YYYY | Bhagamandala, Kodagu | Contractor Copy"`
  - GF plan: Electrical point symbols (orange squares: SB, DB, TV, 15A, USB) + water point symbols (blue circles: C, H, G, WM) + LEGEND box
  - Site layout: External taps (EXT. TAP), overhead water tank (2000L circle), pump (1HP near well), electricity meter (EB METER near gate)
  - Pillar positions: GF `[5, 13, 21, 27, 37]`, Front elevation `[5, 13, 21, 27, 38]`, door at x=30 width=4
- `Bhagamandala_House_Construction_Plan_v4.md` — Complete English plan (+ external tap specs, washing machine point)
- `Bhagamandala_Cost_Estimate_PRIVATE_v4.md` — Cost details (PRIVATE)
- `Bhagamandala_Mane_Kannada_v4.md` — Kannada version (sections 10-16 added: bathroom fixtures, kitchen, electrical, water points, furniture, area summary, flooring breakdown)
- `Bhagamandala_Veedu_Malayalam_v4.md` — Malayalam version (sections 10-16 added: matching Kannada component details in Malayalam)
- `3d-viewer/index.html` — Interactive 3D walkthrough (Three.js WebGL)
- `docs/index.html` — Landing page website (generated by `build_website.py`)
- `docs/viewer.html` — 3D viewer copy for GitHub Pages
- `pipeline.py` — 4-step automation: `--images` → `--pdfs` → `--sync` → `--context`. Uses venv python.
- `build_website.py` — Generates docs/index.html + copies viewer + copies plan images to docs/img/
- `generate_pdfs.py` — PDF generator (requires fpdf from venv; use `python3 pipeline.py --pdfs` not direct)
- v3 files retained for reference

## PIPELINE & WORKFLOW
- **Run pipeline:** `cd house-plan && python3 pipeline.py --all` (or `--images`, `--pdfs`, `--sync`, `--context`)
- **PDF generation:** Must use `python3 pipeline.py --pdfs` (not `python3 generate_pdfs.py` directly — fpdf is in the venv at `../.venv/bin/python3`)
- **3D sync:** After editing `3d-viewer/index.html`, run `cp 3d-viewer/index.html docs/viewer.html`
- **Push to GitHub:**
  ```
  gh auth switch --user rakshith-ponnappa
  git add -A && git commit -m "message" && git push
  gh auth switch --user zz-spr-ext_fiveb
  ```
- **Local dev server:** `cd 3d-viewer && python3 -m http.server 8899`

## 3D INTERACTIVE VIEWER
- **Location:** `3d-viewer/index.html` — single-file HTML app
- **Tech:** Three.js r0.164.1 (ES modules via CDN), OrbitControls, PBR materials
- **Camera:** Position (16,7,-5), FOV 45°, window.innerWidth sizing
- **Features:** Orbit/zoom/pan, room click→fly-to + detail popup, explode view (GF/FF separation), roof toggle, X-Ray (transparent walls), day/night mode, section cut, floor selector (All/GF/FF/Site)
- **peekWalls():** Auto-transparent walls when camera is inside a room (bounding box intersection) — lets you see bathroom interiors
- **Data:** All room dimensions, Vastu directions, wall finishes, flooring, features per room
- **Heritage:** Laterite bedrooms tagged with Kodagu Ainmane heritage badge + ಜಂಬಿಟ್ ಕಲ್ಲು description
- **Site:** Plot boundary, compound wall, road, driveway, trees, garage, coffee drying yard, Tulsi Vrindavan
- **Serve:** `cd 3d-viewer && python3 -m http.server 8899` → open http://localhost:8899

### 3D Viewer — Bathroom Fixtures & Components (added Apr 2026)
- **Shower enclosures:** Glass partitions in all 3 bathrooms (semi-transparent material)
- **Rain shower heads:** Chrome disc on arm in each bathroom
- **Geysers:** 25L white boxes mounted on walls (3 bathrooms)
- **Mirrors:** Reflective material rectangles above basins
- **Towel rods:** Chrome bars near showers
- **Kitchen:** Chimney + hood over cooktop, washing machine in NE corner
- **Switchboards:** 7 locations (hall, master, BR2, kitchen, FF master, family hall, work room)
- **MCB/DB board:** Store room wall

### 3D Viewer — External Components (added Apr 2026)
- **External water taps:** 2 — entrance right (feet washing), parking left (garden/car wash)
- **Overhead water tank:** 2000L on terrace with 4-leg stand
- **Electricity meter board:** Near gate on compound wall
- **Pillar positions:** [5, 13, 21, 27, 37] at z=3 — pillar at x=27 (was x=29) for 3ft clearance from main door at x=30-34

## WEBSITE & GITHUB PAGES
- **Repo:** `rakshith-ponnappa/bhagamandala-house-3d` (public)
- **Live URL:** https://rakshith-ponnappa.github.io/bhagamandala-house-3d/
- **Landing page:** `docs/index.html` (generated by `build_website.py`) — Hero, About (3D iframe), Gallery (6 plan images with lightbox), Specs, Materials, Heritage, CTA, Footer
- **3D Viewer:** `docs/viewer.html` (copy of `3d-viewer/index.html`) — must sync: `cp 3d-viewer/index.html docs/viewer.html`
- **Deployment:** Branch-based GitHub Pages from `docs/` folder (legacy build_type). GitHub Actions failed due to billing hold — bypassed with branch deploy.
- **GitHub CLI:** 3 accounts. Must `gh auth switch --user rakshith-ponnappa` before push, `gh auth switch --user zz-spr-ext_fiveb` after.

## KODAGU HERITAGE (ADDED v4.1)
- **Owner identity:** Kodagu Gowda (indigenous community), speaks Hare Bashe (ಹರೆ ಭಾಷೆ)
- **Bedroom walls:** Exposed laterite (ಜಂಬಿಟ್ ಕಲ್ಲು) + linseed oil finish — NO plaster, NO paint
- **Rooms affected:** Master BR (GF), BR2 (GF), FF Master BR — all 3 bedrooms
- **Other rooms:** Still plastered + painted (hall, kitchen, baths, passage, work room)
- **Benefits:** Heritage Ainmane aesthetic, saves ~₹1L (no plaster/paint), no repainting every 3-5 years, naturally breathes (ideal for 5,000mm/yr rainfall)
- **Linseed oil:** 2 coats raw + 1 coat boiled, re-apply every 3-5 years

## VASTU
- Main door: East (road) ✓
- NE: Hall + Pooja ✓
- SE: Kitchen ✓
- SW: Master BR ✓
- NW: Guest BR ✓
- Baths: Central service strip ✓
- FF Work Room: NE (knowledge) ✓

## COST SUMMARY (v4.1 — with laterite savings)
- Building G+1 (~2,900 sqft @ ₹1,900): ₹55.1L
- External structures: ₹6.8L
- Compound wall (7' safety): ₹5.5L
- Safety (CCTV, grills, pillars): ₹2.85L
- MEP + finishes + solar: ~₹20.4L (reduced: no plaster/paint on 3 bedrooms)
- Linseed oil treatment: ₹0.1L
- Misc + contingency: ₹9.39L
- **TOTAL: ~₹99.8L** (under ₹1 Cr with laterite savings!)


## RECENT CHANGES (April 2026 Session)
1. **Pillar-door fix:** Moved pillar from x=29 to x=27 (3ft clearance from main door x=30-34). Updated 3D viewer + plan generator + front elevation.
2. **Bathroom fixtures in 3D:** Shower glass enclosures, rain showers, geysers 25L, mirrors, towel rods (all 3 bathrooms)
3. **Kitchen components in 3D:** Chimney + hood, washing machine
4. **Electrical in 3D:** 7 switchboards, MCB/DB board in store room
5. **External components in 3D:** 2 water taps (entrance + parking), overhead 2000L tank on terrace, electricity meter near gate
6. **GF plan symbols:** Electrical points (orange squares) + water points (blue circles) + legend box
7. **Site layout additions:** External taps, overhead tank, pump, EB meter
8. **Date stamps:** All 6 plan images now auto-stamp with `"DD Month YYYY | Bhagamandala, Kodagu | Contractor Copy"`
9. **Kannada doc (sections 10-16):** Bathroom fixtures table, kitchen components, electrical schedule (22 lights, 9 fans, 37 5A, 14 15A), water points (15 cold, 6 hot, 15 drain + 2 external), furniture with dimensions, area statement (2,909 sqft), flooring breakdown (2,472 sqft)
10. **Malayalam doc (sections 10-16):** Same 7 sections as Kannada, fully in Malayalam
11. **English doc updates:** External water tap specs + washing machine point added to plumbing/electrical sections
12. **Landing page website:** `build_website.py` generates `docs/index.html` with hero, about (3D iframe), gallery (6 images), specs, materials, heritage sections
13. **GitHub Pages live:** https://rakshith-ponnappa.github.io/bhagamandala-house-3d/
14. **Camera fix:** Position (16,7,-5), FOV 45°
15. **peekWalls():** Auto-transparent walls when camera enters a room (bathroom interior visibility)

---
Last updated: 2026-04-05
